const DEFAULT_API_BASE_URL = "https://api.mrbreado.com/api";

export const API_BASE_URL =
  (import.meta.env.VITE_API_BASE_URL as string | undefined)?.replace(/\/$/, "") ||
  DEFAULT_API_BASE_URL;

export const ADMIN_LOGO_URL = "https://res.cloudinary.com/dswsz53xi/image/upload/v1780431123/logo_qbyjg5.png";

export const endpoints = {
  auth: {
    login: "/auth/login",
    logout: "/auth/logout",
    register: "/auth/register",
  },
  platform: {
    publicSettings: "/platform/settings",
    adminSettings: "/platform/admin/settings",
  },
  admin: {
    profile: "/admin/profile",
    serviceArea: "/admin/service-area",
    verifications: "/admin/verifications",
    verificationsAll: "/admin/verifications/all",
    verificationRequestsAlias: "/admin/verification-requests",
    serviceAreaVerificationsAlias: "/admin/service-area-verifications",
    verificationApprove: (id: number | string) => `/admin/verifications/${id}/approve`,
    verificationReject: (id: number | string) => `/admin/verifications/${id}/reject`,
    restaurantVerificationStatus: (id: number | string) => `/admin/verifications/restaurants/${id}/status`,
    riderVerificationStatus: (id: number | string) => `/admin/verifications/riders/${id}/status`,
    accountProfile: "/admin/account/profile",
    updateProfile: "/admin/profile",
    updateEmail: "/admin/account/email",
    updateEmailOtp: "/admin/account/email/otp",
    updatePassword: "/admin/account/password",
    updatePasswordOtp: "/admin/account/password/otp",
    updatePhone: "/admin/account/phone",
    gstinUpdate: "/admin/account/profile/gstin",

    dashboard: "/admin/dashboard",
    dashboardOverview: "/admin/dashboard/overview",
    dashboardRevenue: "/admin/dashboard/revenue",
    dashboardPayments: "/admin/dashboard/payments",
    dashboardUserGrowth: "/admin/dashboard/user-growth",
    dashboardOrderStatusChart: "/admin/dashboard/order-status-chart",
    dashboardRecentOrders: "/admin/dashboard/recent-orders",
    dashboardTrendingMenu: "/admin/dashboard/trending-menu",
    dashboardPopularRestaurants: "/admin/dashboard/popular-restaurants",
    dashboardTopRestaurants: "/admin/dashboard/top-restaurants",
    mrBreadoDashboard: "/admin/mr-breado/dashboard",

    users: "/admin/users",
    userById: (id: number | string) => `/admin/users/${id}`,
    userStatus: (id: number | string) => `/admin/users/${id}/status`,
    customers: "/admin/customers",
    customerById: (id: number | string) => `/admin/customers/${id}`,
    customerDetails: (id: number | string) => `/admin/customers/${id}/details`,
    customerOrders: (id: number | string) => `/admin/customers/${id}/orders`,
    customerWallet: (id: number | string) => `/admin/customers/${id}/wallet`,
    customerAddresses: (id: number | string) => `/admin/customers/${id}/addresses`,
    customerWalletTopup: (id: number | string) => `/admin/customers/${id}/wallet/top-up`,
    customersExport: "/admin/customers/export",

    owners: "/admin/owners",
    sellers: "/admin/sellers",
    ownerById: (id: number | string) => `/admin/owners/${id}`,
    ownerDetails: (id: number | string) => `/admin/owners/${id}/details`,
    ownerRestaurants: (id: number | string) => `/admin/owners/${id}/restaurants`,
    ownerWallet: (id: number | string) => `/admin/owners/${id}/wallet`,
    ownerSubscriptions: (id: number | string) => `/admin/owners/${id}/subscriptions`,
    ownerStatus: (id: number | string) => `/admin/owners/${id}/status`,
    ownerVerification: (id: number | string) => `/admin/owners/${id}/verification`,
    ownersExport: "/admin/owners/export",

    restaurants: "/admin/restaurants",
    restaurantById: (id: number | string) => `/admin/restaurants/${id}`,
    restaurantDetails: (id: number | string) => `/admin/restaurants/${id}/details`,
    restaurantOrders: (id: number | string) => `/admin/restaurants/${id}/orders`,
    restaurantProducts: (id: number | string) => `/admin/restaurants/${id}/products`,
    restaurantReviews: (id: number | string) => `/admin/restaurants/${id}/reviews`,
    restaurantWallet: (id: number | string) => `/admin/restaurants/${id}/wallet`,
    restaurantStatus: (id: number | string) => `/admin/restaurants/${id}/status`,
    restaurantOnlineStatus: (id: number | string) => `/admin/restaurants/${id}/online-status`,
    restaurantOpeningHours: (id: number | string) => `/admin/restaurants/${id}/opening-hours`,
    restaurantJoinRequests: "/admin/restaurants/join-requests",
    restaurantJoinRequestById: (id: number | string) => `/admin/restaurants/join-requests/${id}`,
    restaurantJoinVerify: (id: number | string) => `/admin/restaurants/join-requests/${id}/verify`,
    restaurantJoinApprove: (id: number | string) => `/admin/restaurants/join-requests/${id}/approve`,
    restaurantJoinReject: (id: number | string) => `/admin/restaurants/join-requests/${id}/reject`,
    restaurantsExport: "/admin/restaurants/export",

    drivers: "/admin/drivers",
    driverById: (id: number | string) => `/admin/drivers/${id}`,
    driverStatus: (id: number | string) => `/admin/drivers/${id}/status`,
    driverVerification: (id: number | string) => `/admin/drivers/${id}/verification`,
    driverVerificationRequests: "/admin/drivers/verification-requests",
    driverVerificationDetails: (id: number | string) => `/admin/drivers/${id}/verification-details`,
    driverApprove: (id: number | string) => `/admin/drivers/${id}/approve`,
    driverReject: (id: number | string) => `/admin/drivers/${id}/reject`,
    driversExport: "/admin/drivers/export",
    driversCash: "/admin/drivers/cash",
    verifyDriverCash: (driverId: number | string) => `/admin/drivers/${driverId}/cash-deposit/verify`,
    driverCashTx: (driverId: number | string) => `/admin/drivers/${driverId}/cash-transactions`,

    products: "/admin/products",
    productById: (id: number | string) => `/admin/products/${id}`,
    productDetails: (id: number | string) => `/admin/products/${id}/details`,
    productStock: (id: number | string) => `/admin/products/${id}/stock`,
    productVisibility: (id: number | string) => `/admin/products/${id}/visibility`,
    productAddons: (id: number | string) => `/admin/products/${id}/addons`,
    productAddonById: (id: number | string, addonId: number | string) => `/admin/products/${id}/addons/${addonId}`,
    productsExport: "/admin/products/export",

    categories: "/admin/categories",
    categorySummary: "/admin/categories/summary",
    categoryById: (id: number | string) => `/admin/categories/${id}`,
    categoryStatus: (id: number | string) => `/admin/categories/${id}/status`,
    categorySubcategories: (id: number | string) => `/admin/categories/${id}/subcategories`,
    subcategoryById: (id: number | string) => `/admin/subcategories/${id}`,
    subcategoryStatus: (id: number | string) => `/admin/subcategories/${id}/status`,
    categoryAliases: "/admin/category",
    foodCategoriesAdmin: "/admin/food-categories",

    publicCategories: "/categories",
    publicSubCategories: "/categories/sub-categories",
    publicFoodCategories: "/food-categories",

    cuisine: "/admin/cuisines",
    cuisines: "/admin/cuisines",

    banners: "/admin/banners",
    bannerById: (id: number | string) => `/admin/banners/${id}`,
    bannerStatus: (id: number | string) => `/admin/banners/${id}/status`,
    offers: "/admin/offers",
    offerById: (id: number | string) => `/admin/offers/${id}`,
    offerStatus: (id: number | string) => `/admin/offers/${id}/status`,
    coupons: "/admin/coupons",
    couponById: (id: number | string) => `/admin/coupons/${id}`,
    couponStatus: (id: number | string) => `/admin/coupons/${id}/status`,

    paymentsSummary: "/admin/payments/summary",
    paymentLedger: "/admin/payment-ledger",
    paymentSettings: "/admin/payment-settings",
    paymentGatewaySettings: "/admin/finance/payment-gateways",
    paymentGatewayByCode: (code: string) => `/admin/finance/payment-gateways/${code}`,
    mrBreadoPayments: "/admin/mr-breado/payments",
    settlements: "/admin/restaurant-settlements",
    generateWeeklySettlement: (restaurantId: number | string) => `/admin/restaurant-settlements/${restaurantId}/generate-weekly`,
    markSettlementPaid: (settlementId: number | string) => `/admin/restaurant-settlements/${settlementId}/mark-paid`,
    sellerPayoutAccounts: "/admin/seller-payout-accounts",
    verifySellerPayout: (accountId: number | string) => `/admin/seller-payout-accounts/${accountId}/verify`,

    settings: "/admin/settings",
    restaurantSettings: "/admin/settings/restaurant",
    driverSettings: "/admin/settings/driver",
    mapSettings: "/admin/settings/map",
    commissionSettings: "/admin/settings/commission",
    vendorCommissionSettings: "/admin/settings/commission/vendor",
    driverCommissionSettings: "/admin/settings/commission/driver",
    platformFeeSettings: "/admin/settings/platform-fee",

    supportDashboard: "/admin/support/dashboard",
    supportTickets: "/admin/support/tickets",
    supportTicketById: (id: number | string) => `/admin/support/tickets/${id}`,
    supportTicketToday: "/admin/support/tickets/today",
    supportTicketAccept: (id: number | string) => `/admin/support/tickets/${id}/accept`,
    supportTicketStatus: (id: number | string) => `/admin/support/tickets/${id}/status`,
    supportTicketReply: (id: number | string) => `/admin/support/tickets/${id}/reply`,

    notifications: {
      send: "/admin/notifications/send",
      sendToAll: "/admin/notifications/send-to-all",
      sendToCustomers: "/admin/notifications/send-to-customers",
      sendToSellers: "/admin/notifications/send-to-sellers",
      sendToDrivers: "/admin/notifications/send-to-drivers",
    },
    customerMessages: "/admin/customer-messages/send",
    sellerMessages: "/admin/seller-messages",

    roles: "/admin/roles",
    roleAliases: "/admin/role",
    rolePermissions: (code: string) => `/admin/roles/${code}/permissions`,
    reviews: "/admin/reviews",
    restaurantReports: "/admin/restaurant-reports",
    reportStatus: (reportId: number | string) => `/admin/restaurant-reports/${reportId}/status`,
    uploadOfferImage: "/admin/uploads/offer-image",

    mrBreado: {
      dashboard: "/admin/mr-breado/dashboard",
      orders: "/admin/mr-breado/orders",
      orderById: (id: number | string) => `/admin/mr-breado/orders/${id}`,
      accept: (id: number | string) => `/admin/mr-breado/orders/${id}/accept`,
      preparing: (id: number | string) => `/admin/mr-breado/orders/${id}/preparing`,
      ready: (id: number | string) => `/admin/mr-breado/orders/${id}/ready`,
      reject: (id: number | string) => `/admin/mr-breado/orders/${id}/reject`,
      invoicePdf: (id: number | string) => `/admin/mr-breado/orders/${id}/invoice.pdf`,
      sendInvoice: (id: number | string) => `/admin/mr-breado/orders/${id}/invoice/send-to-customer`,
      products: "/admin/mr-breado/products",
      productById: (id: number | string) => `/admin/mr-breado/products/${id}`,
      productAvailability: (id: number | string) => `/admin/mr-breado/products/${id}/availability`,
      productStock: (id: number | string) => `/admin/mr-breado/products/${id}/stock`,
      template: "/admin/mr-breado/products/template",
      import: "/admin/mr-breado/products/import",
      export: "/admin/mr-breado/products/export",
      restaurant: "/admin/mr-breado/restaurant",
      restaurantStatus: "/admin/mr-breado/restaurant/status",
    },
  },
} as const;
